name: engelsiz_admin
description: An admin application for engelsiz.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  flutter_login: ^4.1.1
  flutter_riverpod: ^2.1.3
  firebase_auth: ^4.2.5
  flex_color_scheme: ^6.1.2
  google_fonts: ^4.0.1
  flutter_form_builder: ^7.5.0
  intl: ^0.17.0
  form_builder_validators: ^8.3.0
  flutter_multi_formatter: ^2.10.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^1.1.1
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  riverpod_generator: ^1.1.1

flutter:

  uses-material-design: true
