name: engelsiz_admin
description: An admin application for engelsiz.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^3.4.2
  firebase_core: ^1.20.0
  flutter_login: ^4.0.0
  flutter_riverpod: ^1.0.4
  firebase_auth: ^3.6.1
  flex_color_scheme: ^5.1.0
  google_fonts: ^3.0.1
  flutter_form_builder: ^7.5.0
  intl: ^0.17.0
  form_builder_validators: ^8.3.0
  flutter_multi_formatter: ^2.5.8
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true
